name: mal_down
description: MAL Down - Flutter Android app for MyAnimeList image downloading
publish_to: 'none'
version: 1.0.9+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.8

  # Database + Local Storage
  sqflite: ^2.5.0
  path_provider: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking + Utils
  dio: ^5.7.0
  connectivity_plus: ^6.0.2
  xml: ^6.7.0
  image: ^4.5.2

  # Cache + EXIF
  cached_network_image: ^3.5.1
  flutter_cache_manager: ^3.4.3
  exif: ^3.5.0
  native_exif: ^0.6.3

  # File Picker + Permissions
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  path: ^1.9.0

  # Background Work + Notifications
  workmanager: ^0.5.3
  flutter_local_notifications: ^18.0.0

  # Utils
  intl: ^0.19.1
  uuid: ^4.5.0
  json_annotation: ^4.9.0
  dartz: ^0.11.2
  logger: ^2.2.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.6.0

  # Riverpod
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  riverpod_generator: ^2.5.1
  json_serializable: ^6.8.2

  # Correct version for Dart 3.8
  hive_generator: ^2.0.1

  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
