name: mal_down
description: MAL Down - Flutter Android app for MyAnimeList image downloading compatible with Dart 3.8.0
publish_to: 'none'
version: 1.0.3+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.0
  riverpod_annotation: ^2.5.0

  cupertino_icons: ^1.0.7
  google_fonts: ^6.1.0
  flutter_animate: ^4.6.0

  sqflite: ^2.4.0
  path_provider: ^2.4.0
  shared_preferences: ^2.3.0
  hive: ^2.3.0
  hive_flutter: ^1.2.0

  dio: ^5.6.0
  connectivity_plus: ^5.1.0

  xml: ^6.4.3

  image: ^4.3.0
  cached_network_image: ^3.4.0
  flutter_cache_manager: ^3.4.1

  exif: ^3.4.0
  native_exif: ^0.6.0

  file_picker: ^6.2.0
  permission_handler: ^11.2.0
  path: ^1.8.4

  workmanager: ^0.5.3
  flutter_local_notifications: ^16.5.0

  intl: ^0.19.0
  uuid: ^4.2.2
  json_annotation: ^4.9.0
  equatable: ^2.1.0
  dartz: ^0.11.0

  logger: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.5.0
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  hive_generator: ^2.1.0

  flutter_lints: ^6.0.0
  very_good_analysis: ^6.0.0

  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
